version: '3'
services:
  challenge-customer-api:
    image: challenge-customer-api:latest
    env_file:
      - .env    

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
