service: customer-api

frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  individually: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  profile: particular
  region: us-east-1
  environment:
    DYNAMODB_CUSTOMERS: ${ssm:${self:custom.stage}-dynamodb-customers-table} 

functions:
  create:
    role: ${ssm:${self:custom.stage}-create-iam-role}
    handler: ./src/function/create.handler
    events:
      - http:
          path: customers
          method: post

custom:
  stage: ${opt:stage, self:provider.stage}
